#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

picom &> /dev/null &

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

eww daemon --config "${SCRIPTPATH}"/eww &

eww open --config "${SCRIPTPATH}"/eww bar1
eww open --config "${SCRIPTPATH}"/eww bar2
